# configures spring boot to connect to our docker infra

spring:
  application:
    name: skywatch-backend

  # postgreSQL configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/skywatch
    username: skywatch
    password: skywatch
    driver-class-name: org.postgresql.Driver

  # Hibernate/JPA settings
  jpa:
    hibernate:
      ddl-auto: update # automatically creates/updates DB tables based on our Java entities
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  kafka:
    bootstrap-servers: ${KAFKA_HOST:127.0.0.1}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: skywatch-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.skywatch.backend.model"